### ISSUE TITLE
gstreamer error - no element "whipsink"

### ISSUE THREAD

**Issue by yair-sh** [meetecho/simple-whip-server#11]
Hi, i have fresh ubuntu 23.04. I have installed gstreamer with [this](https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c#install-gstreamer-on-ubuntu-or-debian) , but the excelent whip not exist. any clue ?

**Comment by lminiero** [comment]
That is a different and unrelated effort.
